version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
  redis-node1:
    image: redis:7.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7000:7000"
    volumes:
      - ./redis-cluster/node1/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node1/data:/data
  redis-node2:
    image: redis:7.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7001:7001"
    volumes:
      - ./redis-cluster/node2/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node2/data:/data
  redis-node3:
    image: redis:7.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7002:7002"
    volumes:
      - ./redis-cluster/node3/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node3/data:/data
  redis-node4:
    image: redis:7.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7003:7003"
    volumes:
      - ./redis-cluster/node4/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node4/data:/data
  redis-node5:
    image: redis:7.2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7004:7004"
    volumes:
      - ./redis-cluster/node5/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node5/data:/data
  redis-cluster-init:
    image: redis:7.2
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
    command: >
      sh -c "sleep 20 && echo yes | redis-cli --cluster create redis-node1:7000 redis-node2:7001 redis-node3:7002 redis-node4:7003 redis-node5:7004 --cluster-replicas 1"
    networks:
      - default
