version: '3.8'
services:
  web:
    build: .
    container_name: "web"
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
  redis-node1:
    image: redis:7.2
    container_name: "node-1"
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7000:7000"
    volumes:
      - ./redis-cluster/node1/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node1/data:/data
  redis-node2:
    image: redis:7.2
    container_name: "node-2"
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7001:7001"
    volumes:
      - ./redis-cluster/node2/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node2/data:/data
  redis-node3:
    image: redis:7.2
    container_name: "node-3"
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7002:7002"
    volumes:
      - ./redis-cluster/node3/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node3/data:/data
  redis-node4:
    image: redis:7.2
    container_name: "node-4"
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7003:7003"
    volumes:
      - ./redis-cluster/node4/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node4/data:/data
  redis-node5:
    image: redis:7.2
    container_name: "node-5"
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7004:7004"
    volumes:
      - ./redis-cluster/node5/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node5/data:/data
  redis-node6:
    image: redis:7.2
    container_name: "node-6"
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7005:7005"
    volumes:
      - ./redis-cluster/node6/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-cluster/node6/data:/data
  redis-cluster-init:
    image: redis:7.2
    container_name: "cluster-init"
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
    volumes:
      - ./init-cluster.sh:/init-cluster.sh
    command: sh /init-cluster.sh
    networks:
      - default
